### ISSUE TITLE
Can we have dynamic callback_url/callback_path

### ISSUE THREAD

**Issue by spartan1234** [mkdynamic/omniauth-facebook#215]
I am trying to add API in my existing rails application, it will just return json data, but will have different login space not the same as in existing application
Existing application - after login user will be redirected to his/her profile
New login page for api -- token will be generated and returned in api call.
So, there will be two callback function based upon the login page called, so, how can I dynamically define callback_path based upon the login page called.

**Comment by mkdynamic** [comment]
I think the easiest way is to set a flag in the session before redirecting to FB for authentication, and then check that during the callback. If you want to work on a PR for dynamic callback url/path we'd consider it.

**Comment by abevoelker** [comment]
Sorry to revive an old issue, but would you still be accepting PRs for a dynamic callback URL/path? If so, how would you envision that be implemented? As a query parameter like `display`, `scope`, and `auth_type` are currently handled?

Reason being, I was thinking about appending a [JWT](https://jwt.io/) as a query parameter to my callback URL instead of setting session variables.

**Comment by mkdynamic** [comment]
@abevoelker Allowing the redirect URL or path to by dynamic is a security risk since it lets attackers leak authentication details to URLs they control. However, it should be safe to pass dynamic query string parameters as part of the callback URL.

This used to be possible, but we removed support as part of https://github.com/mkdynamic/omniauth-facebook/pull/221. If you can work on a PR that enables back picking up the query-string as part of the callback_url, would certainly accept that. To avoid potential breakage, I would make that an option which you have to enable.

Re-opening this issue to track.

**Comment by abevoelker** [comment]
Okay thanks, after you mentioned the security risk and seeing how easy it is to break things based on the issue you linked, I decided against it and am going to just use a session variable instead. Sorry, and you can close this issue once again.
