### ISSUE TITLE
Android app login into REST api

### ISSUE THREAD

**Issue by Alxzu** [mkdynamic/omniauth-facebook#231]
Hi, sorry about my english, I will try to be as clear as I can.
I have a Rails Restful Api actually using [devise token auth](https://github.com/lynndylanhurley/devise_token_auth) for authentication. I need to provide a way to login from an Android app. How can I achieve this using omniauth-facebook? Thanks

**Comment by drnluz** [comment]
Hello. I also have a api using devise token auth that I need to integrate with omniauth-facebook for ios/android login. I found the following gem: https://github.com/SoapSeller/omniauth-facebook-access-token. I think that this can solve our problem. I'll test it.

**Comment by simi** [comment]
@drnluz if I remember well, that library is not secure. We're working on same functionality with secured background in https://github.com/mkdynamic/omniauth-facebook/pull/174.

**Comment by drnluz** [comment]
@simi Thanks for the warning. I'll take a look at the PR.

**Comment by fearenales** [comment]
Hi, I'm sorry if I misunderstood, but this is also related to a separated frontend app, right? (actually it's related to any API consumer app that wants to provide Facebook login --  and it doesn't deserve a new issue here).

I'm trying to login in the frontend using FB JS SDK and send the result to the OAuth Facebook Callback URL so that `omniauth-facebook` can exchange for a long-term token. However it's not working because the `fbsr_XXX` cookie isn't available in the API app.

How is it done today?

I've opened a [question](http://stackoverflow.com/questions/36941931/cors-issue-with-facebook-js-sdk-cookie-and-omniauth-facebook) at StackOverflow with further details about it.

Thanks.
